### ISSUE TITLE
Assertion failure on game quit in NOGUI builds

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#2249]
**Game details**
Any game

**Description of the issue / bug**
This message appears on the GNU/Linux console when choosing the "Quit Game" option:

```
pi@raspberrypi:~/psx $ ./duckstation-nogui 
Program directory "/home/pi/psx"
User directory: "/home/pi/.local/share/duckstation"
duckstation-nogui: /home/pi/src/duckstation/dep/cubeb/src/cubeb_alsa.c:1121: alsa_stream_destroy: Assertion `stm && (stm->state == INACTIVE || stm->state == ERROR || stm->state == DRAINING)' failed.
Aborted

```

**Steps to reproduce**
Simply load a game an then quit.

**Enhancements information**
No enhancements active.

**Hardware/software**
Raspberry Pi 4 / X86_64, GNU/Linux, NOGUI build using software renderer and CUBEB audio backend.

**Emulator version**
Current GIT version.

**Comment by stenzek** [comment]
I suspect this is unique to the pi... it's not happening on my odroid-n2.

**Comment by vanfanel** [comment]
@stenzek Hmm. But it's happening in cubeb_alsa.c, it's an assertion failure. Could it be that only the Pi ALSA driver triggers this then?

**Comment by stenzek** [comment]
I'm not getting it on a armv7 raspberry pi4 either. I have seen this before though, so there must be something more to this.

**Comment by vanfanel** [comment]
I am using the vc4-hdmi ALSA device (which is the modern audio device). Maybe you are using the old Broadcom audio?

vc4-hdmi is better because it allows lower audio buffers without cracking (runs on the ARM side)

**Comment by stenzek** [comment]
Can you at least get a backtrace? Set `[CPU]`/`FastmemMode` to `Disabled` in settings to stop backpatching from getting in the way.

**Comment by vanfanel** [comment]
@stenzek Yes, of course, here it is:
```

duckstation-nogui: /home/pi/src/duckstation/dep/cubeb/src/cubeb_alsa.c:1121: alsa_stream_destroy: Assertion `stm && (stm->state == INACTIVE || stm->state == ERROR || stm->state == DRAINING)' failed.

Thread 1 "duckstation-nog" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000007ff79de8e8 in __GI_abort () at abort.c:79
#2  0x0000007ff79e9f60 in __assert_fail_base (fmt=0x7ff7ae3ef0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x5555e31628 "stm && (stm->state == INACTIVE || stm->state == ERROR || stm->state == DRAINING)", 
    file=file@entry=0x5555e311b0 "/home/pi/src/duckstation/dep/cubeb/src/cubeb_alsa.c", line=line@entry=1121, 
    function=function@entry=0x5555e31740 <__PRETTY_FUNCTION__.10869> "alsa_stream_destroy") at assert.c:92
#3  0x0000007ff79e9fc8 in __GI___assert_fail (
    assertion=0x5555e31628 "stm && (stm->state == INACTIVE || stm->state == ERROR || stm->state == DRAINING)", 
    file=0x5555e311b0 "/home/pi/src/duckstation/dep/cubeb/src/cubeb_alsa.c", line=1121, 
    function=0x5555e31740 <__PRETTY_FUNCTION__.10869> "alsa_stream_destroy") at assert.c:101
#4  0x0000005555b81894 in alsa_stream_destroy (stm=0x555a8768d0) at /home/pi/src/duckstation/dep/cubeb/src/cubeb_alsa.c:1119
#5  0x0000005555b7c414 in cubeb_stream_destroy (stream=0x555a8768d0) at /home/pi/src/duckstation/dep/cubeb/src/cubeb.c:384
#6  0x00000055558adac0 in CubebAudioStream::CloseDevice (this=0x555a2e17d0)
    at /home/pi/src/duckstation/src/frontend-common/cubeb_audio_stream.cpp:119
#7  0x00000055558ad5e0 in CubebAudioStream::~CubebAudioStream (this=0x555a2e17d0, __in_chrg=<optimized out>)
    at /home/pi/src/duckstation/src/frontend-common/cubeb_audio_stream.cpp:17
#8  0x00000055558ad608 in CubebAudioStream::~CubebAudioStream (this=0x555a2e17d0, __in_chrg=<optimized out>)
    at /home/pi/src/duckstation/src/frontend-common/cubeb_audio_stream.cpp:18
#9  0x00000055555d3bf4 in std::default_delete<AudioStream>::operator() (this=0x555a2a6600, __ptr=0x555a2e17d0)
    at /usr/include/c++/8/bits/unique_ptr.h:81
#10 0x00000055555d2870 in std::unique_ptr<AudioStream, std::default_delete<AudioStream> >::reset (this=0x555a2a6600, 
    __p=0x555a2e17d0) at /usr/include/c++/8/bits/unique_ptr.h:382
#11 0x00000055555cad64 in HostInterface::DestroySystem (this=0x555a2a65f0)
    at /home/pi/src/duckstation/src/core/host_interface.cpp:161
#12 0x000000555587c3b4 in CommonHostInterface::DestroySystem (this=0x555a2a65f0)
    at /home/pi/src/duckstation/src/frontend-common/common_host_interface.cpp:213
#13 0x000000555587c410 in CommonHostInterface::PowerOffSystem (this=0x555a2a65f0, save_resume_state=false)
    at /home/pi/src/duckstation/src/frontend-common/common_host_interface.cpp:224
#14 0x00000055558b0230 in FullscreenUI::<lambda()>::operator()(void) const (__closure=0x7ffffff3d0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/pi/src/duckstation/src/frontend-common/fullscreen_ui.cpp:583
#15 0x00000055558c45bc in std::_Function_handler<void(), FullscreenUI::DoPowerOff()::<lambda()> >::_M_invoke(const std::_Any_data &)
    (__functor=...) at /usr/include/c++/8/bits/std_function.h:297
#16 0x00000055555c0aa0 in std::function<void ()>::operator()() const (this=0x7ffffff3d0)
    at /usr/include/c++/8/bits/std_function.h:687
#17 0x00000055555bfd38 in NoGUIHostInterface::RunCallbacks (this=0x555a2a65f0)
    at /home/pi/src/duckstation/src/duckstation-nogui/nogui_host_interface.cpp:332
#18 0x00000055555bf7c4 in NoGUIHostInterface::Run (this=0x555a2a65f0)
    at /home/pi/src/duckstation/src/duckstation-nogui/nogui_host_interface.cpp:207
#19 0x00000055555bd260 in Run (host_interface=std::unique_ptr<class NoGUIHostInterface> = {...}, 
    boot_params=std::unique_ptr<struct SystemBootParameters> = {...}) at /home/pi/src/duckstation/src/duckstation-nogui/main.cpp:76
#20 0x00000055555bd378 in main (argc=1, argv=0x7ffffff638) at /home/pi/src/duckstation/src/duckstation-nogui/main.cpp:140

```

**Comment by stenzek** [comment]
See if https://github.com/stenzek/duckstation/commit/093904f930b61b1a015aa2256e8ea1fbf426d841 makes any difference (might be a race). I still can't trigger it here.

**Comment by vanfanel** [comment]
@stenzek Yep, that did it! No more assertion failures on game quit.
Let me do some more tests tomorrow, but first runs didn't give me any :)
