### ISSUE TITLE
[libretro - Linux - Vulkan - Intel iGPU] Crash on successive load content

### ISSUE THREAD

**Issue by jdgleaver** [stenzek/duckstation#672]
When running the libretro core under Linux using the Vulkan backend with Intel integrated graphics, the first 'load content' operation works correctly - but attempting to load content a second time within the same session results in a crash, with the following assertion:

```
Assertion failed: 'Context should have been destroyed by now' in function ~VulkanHostDisplay (/home/buildbot/buildbot/linux_x86_64/libretro-duckstation/src/frontend-common/vulkan_host_display.cpp:95)
Aborting application.
Aborted (core dumped) 
```

I get the same result on two machines:

- OpenSUSE Leap 15.2 + Intel HD Graphics 5500
- OpenSUSE Tumbleweed + Intel UHD Graphics 605

However, the issue does not manifest under Linux when using Nvidia graphics (with the official binary blob driver) - content can be launched any number of times, and no errors occur. So it may be the case that this is an Intel driver bug...

**Comment by stenzek** [comment]
Hmm, any chance you could get a backtrace for this? All the obvious paths clean it up as expected.

**Comment by jdgleaver** [comment]
With your latest commit, it no longer complains about the context - but it still crashes on the second 'load content'. Here's a backtrace: (apologies for not including one in the original bug report!)

```c++
retroarch: ../dep/glslang/OGLCompilersDLL/InitializeDll.cpp:109: bool glslang::InitThread(): Assertion `0 && "InitThread(): Unable to set init flag."' failed.

Thread 1 "retroarch" received signal SIGABRT, Aborted.
0x00007fffef3ac520 in raise () from /lib64/libc.so.6
 (gdb) bt
#0  0x00007fffef3ac520 in raise () from /lib64/libc.so.6
#1  0x00007fffef3adb01 in abort () from /lib64/libc.so.6
#2  0x00007fffef3a4b1a in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fffef3a4b92 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffb5ae52e6 in glslang::InitThread () at ../dep/glslang/OGLCompilersDLL/InitializeDll.cpp:109
#5  0x00007fffb5ab59e0 in glslang::TShader::parse (this=0x1f850b0, 
    builtInResources=0x7fffb5cc67a0 <glslang::DefaultTBuiltInResource>, defaultVersion=450, defaultProfile=ECoreProfile, 
    forceDefaultVersionAndProfile=false, forwardCompatible=true, messages=24, includer=...)
    at ../dep/glslang/glslang/MachineIndependent/ShaderLang.cpp:1849
#6  0x00007fffb5981e22 in Vulkan::ShaderCompiler::CompileShaderToSPV (stage=EShLangVertex, stage_filename=0x7fffb5c751f8 "vs", 
    source="\n#version 450 core\n\nlayout(push_constant) uniform PushConstants {\n  uniform vec4 u_src_rect;\n};\n\nlayout(location = 0) out vec2 v_tex0;\n\nvoid main()\n{\n  vec2 pos = vec2(float((gl_VertexIndex << 1) & 2)"...)
    at ../src/common/vulkan/shader_compiler.cpp:70
#7  0x00007fffb59824d5 in Vulkan::ShaderCompiler::CompileShader (type=Vulkan::ShaderCompiler::Type::Vertex, 
    source_code="\n#version 450 core\n\nlayout(push_constant) uniform PushConstants {\n  uniform vec4 u_src_rect;\n};\n\nlayout(location = 0) out vec2 v_tex0;\n\nvoid main()\n{\n  vec2 pos = vec2(float((gl_VertexIndex << 1) & 2)"..., debug=false)
    at ../src/common/vulkan/shader_compiler.cpp:157
#8  0x00007fffb597f0ca in Vulkan::ShaderCache::CompileAndAddShaderSPV (this=0x20012c0, key=..., 
    shader_code="\n#version 450 core\n\nlayout(push_constant) uniform PushConstants {\n  uniform vec4 u_src_rect;\n};\n\nlayout(location = 0) out vec2 v_tex0;\n\nvoid main()\n{\n  vec2 pos = vec2(float((gl_VertexIndex << 1) & 2)"...)
    at ../src/common/vulkan/shader_cache.cpp:487
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007fffb597ec52 in Vulkan::ShaderCache::GetShaderSPV (this=0x20012c0, type=Vulkan::ShaderCompiler::Type::Vertex, 
    shader_code="\n#version 450 core\n\nlayout(push_constant) uniform PushConstants {\n  uniform vec4 u_src_rect;\n};\n\nlayout(location = 0) out vec2 v_tex0;\n\nvoid main()\n{\n  vec2 pos = vec2(float((gl_VertexIndex << 1) & 2)"...)
    at ../src/common/vulkan/shader_cache.cpp:431
#10 0x00007fffb597ee2d in Vulkan::ShaderCache::GetShaderModule (this=0x20012c0, type=Vulkan::ShaderCompiler::Type::Vertex, 
    shader_code="\n#version 450 core\n\nlayout(push_constant) uniform PushConstants {\n  uniform vec4 u_src_rect;\n};\n\nlayout(location = 0) out vec2 v_tex0;\n\nvoid main()\n{\n  vec2 pos = vec2(float((gl_VertexIndex << 1) & 2)"...)
    at ../src/common/vulkan/shader_cache.cpp:446
#11 0x00007fffb597ef96 in Vulkan::ShaderCache::GetVertexShader (this=0x20012c0, 
    shader_code="\n#version 450 core\n\nlayout(push_constant) uniform PushConstants {\n  uniform vec4 u_src_rect;\n};\n\nlayout(location = 0) out vec2 v_tex0;\n\nvoid main()\n{\n  vec2 pos = vec2(float((gl_VertexIndex << 1) & 2)"...)
    at ../src/common/vulkan/shader_cache.cpp:466
#12 0x00007fffb5a465dd in FrontendCommon::VulkanHostDisplay::CreateResources (this=0x7fffd0000bb0)
    at ../src/frontend-common/vulkan_host_display.cpp:338
#13 0x00007fffb584e669 in LibretroVulkanHostDisplay::CreateResources (this=0x7fffd0000bb0)
    at ../src/duckstation-libretro/libretro_vulkan_host_display.cpp:131
#14 0x00007fffb5a46386 in FrontendCommon::VulkanHostDisplay::InitializeRenderDevice (this=0x7fffd0000bb0, shader_cache_directory="", 
    debug_device=false) at ../src/frontend-common/vulkan_host_display.cpp:250
#15 0x00007fffb5846242 in LibretroHostInterface::SwitchToHardwareRenderer (this=0x7fffb60a4a60 <g_libretro_host_interface>)
    at ../src/duckstation-libretro/libretro_host_interface.cpp:879
#16 0x00007fffb5845ef4 in LibretroHostInterface::HardwareRendererContextReset ()
--Type <RET> for more, q to quit, c to continue without paging--
    at ../src/duckstation-libretro/libretro_host_interface.cpp:826
#17 0x0000000000497662 in drivers_init (p_rarch=0x13eab20 <rarch_st>, flags=2047) at retroarch.c:34258
#18 0x000000000049d4f3 in retroarch_main_init (argc=10, argv=0x7fffffff70e0) at retroarch.c:36576
#19 0x00000000004b952f in content_load (info=0x7fffffff7260, p_content=0x1452920 <rarch_st+425472>) at tasks/task_content.c:605
#20 0x00000000004bac29 in command_event_cmd_exec (p_content=0x1452920 <rarch_st+425472>, 
    data=0x7fffffff9480 "/home/james/Documents/ROMs/PSX/Air Hockey (USA).chd", content_ctx=0x7fffffff72d0, launched_from_cli=false, 
    error_string=0x7fffffff72c8) at tasks/task_content.c:1459
#21 0x00000000004bb3cf in task_push_load_content_from_playlist_from_menu (
    core_path=0x7fffffff7480 "/home/james/.config/retroarch/cores/duckstation_libretro.so", 
    fullpath=0x7fffffff9480 "/home/james/Documents/ROMs/PSX/Air Hockey (USA).chd", label=0x0, content_info=0x7fffffff7390, cb=0x0, 
    user_data=0x0) at tasks/task_content.c:1723
#22 0x0000000000778c82 in default_action_ok_load_content_from_playlist_from_menu (
    _path=0x7fffffff7480 "/home/james/.config/retroarch/cores/duckstation_libretro.so", 
    path=0x7fffffff9480 "/home/james/Documents/ROMs/PSX/Air Hockey (USA).chd", entry_label=0x0) at menu/cbs/menu_cbs_ok.c:1888
#23 0x0000000000779ca4 in action_ok_playlist_entry_collection (path=0x7fffffffcb68 "Run", label=0x7fffffffcc67 "collection", type=7, 
    idx=0, entry_idx=0) at menu/cbs/menu_cbs_ok.c:2262
#24 0x000000000045ae3f in generic_menu_entry_action (userdata=0x1db91a0, entry=0x7fffffffcb50, i=0, action=MENU_ACTION_OK)
    at retroarch.c:4704
#25 0x000000000070c8e8 in materialui_menu_entry_action (userdata=0x1db91a0, entry=0x7fffffffcb50, i=0, action=MENU_ACTION_OK)
    at menu/drivers/materialui.c:8279
#26 0x000000000045ca60 in menu_entry_action (entry=0x7fffffffcb50, i=0, action=MENU_ACTION_OK) at retroarch.c:5405
--Type <RET> for more, q to quit, c to continue without paging--
#27 0x000000000045aac8 in generic_menu_iterate (p_rarch=0x13eab20 <rarch_st>, data=0x1db1160, userdata=0x1db91a0, 
    action=MENU_ACTION_OK, current_time=509034370) at retroarch.c:4626
#28 0x000000000045f89e in menu_driver_iterate (iterate=0x7fffffffd630, current_time=509034370) at retroarch.c:7006
#29 0x00000000004a14a5 in runloop_check_state (p_rarch=0x13eab20 <rarch_st>, settings=0x7ffff7f5b010, current_time=509034370)
    at retroarch.c:38661
#30 0x00000000004a2e51 in runloop_iterate () at retroarch.c:39253
#31 0x0000000000473a47 in rarch_main (argc=1, argv=0x7fffffffda98, data=0x0) at retroarch.c:17281
#32 0x000000000061a4a5 in main (argc=1, argv=0x7fffffffda98) at ui/drivers/qt/ui_qt_application.cpp:151
```
