### ISSUE TITLE
Crash while trying to print bios filename

### ISSUE THREAD

**Issue by Ziemas** [stenzek/duckstation#9]
SIGSEGV in __strlen_avx2

```
Thread 3 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1738700 (LWP 201612)]
0x00007ffff66006f5 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff66006f5 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00007ffff650b61e in __vfprintf_internal () from /usr/lib/libc.so.6
#2  0x00007ffff651d40a in __vsnprintf_internal () from /usr/lib/libc.so.6
#3  0x00005555556b05cb in Log::Writev (channelName=0x555555807f68 "HostInterface", 
    functionName=0x555555807fd2 "GetBIOSImage", level=LOGLEVEL_INFO, format=0x555555807fdf "Using BIOS from '%s'", 
    ap=0x7ffff17373f0) at /home/ziemas/src/duckstation/src/common/log.cpp:331
#4  0x00005555556b04e4 in Log::Writef (channelName=0x555555807f68 "HostInterface", 
    functionName=0x555555807fd2 "GetBIOSImage", level=LOGLEVEL_INFO, format=0x555555807fdf "Using BIOS from '%s'")
    at /home/ziemas/src/duckstation/src/common/log.cpp:311
#5  0x00005555555dedee in HostInterface::GetBIOSImage (this=0x555555973a50, region=ConsoleRegion::NTSC_U)
    at /home/ziemas/src/duckstation/src/core/host_interface.cpp:316

```

Printing seems pretty messed up in general.
```
[    1.5884] I/OpenGLDisplayWindow: Got a desktop OpenGL 1435629569.-212292416 context
[    1.6179] I/GPU_HW_OpenGL: GL_VERSION: 
[    1.6179] I/GPU_HW_OpenGL: GL_RENDERER: úRé
[    1.6179] I/GPU_HW_OpenGL: Max texture size: 1437602488x-467984352
[    1.6179] I/GPU_HW_OpenGL: Max line width: 2
[    1.6180] I/GPU_HW_OpenGL: Maximum resolution scale is 4050873968
[    1.6180] I/GPU_HW_OpenGL: Uniform buffer offset alignment: 1
[    1.6180] I/GPU_HW_OpenGL: Max texel buffer size: 1
[    1.6527] I/HostInterface: Syncing to @vsñÿ`UUU
```

**Comment by stenzek** [comment]
That seems strange. Which compiler/distro are you running?

**Comment by Ziemas** [comment]
Arch Linux with GCC 9.2.0

**Comment by stenzek** [comment]
Okay, thanks. I'll look into it.

**Comment by stenzek** [comment]
Should be fixed now. I really need to set up CI with tests on Linux to catch things like this, since I mostly work on Windows.

**Comment by Ziemas** [comment]
Yup, now it works. Thanks.
